const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
function setup(){
 const sid=['99','00001'].join(''),other=['99','00002'].join(''),secret='synthetic-'.repeat(5),cache=new Map();let reads=0;
 const props={APP_ENV:'staging',CLOUDFLARE_CARD_ADAPTER_SECRET:secret};
 const tables={Main_2569:[['header'],['',sid]],Deeds_2569:[['header'],['own',sid,6,1,'2026-09-06','synthetic','','','','pending','2026-09-06'],['other',other,6,1,'2026-09-06','private synthetic','','','','pending','2026-09-06']]};
 const context=vm.createContext({console,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]})},SpreadsheetApp:{getActiveSpreadsheet:()=>({getSheetByName:n=>tables[n]?{getDataRange:()=>({getValues:()=>{reads++;return tables[n]}})}:null})},LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})},CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v)})},Utilities:{newBlob:s=>({getBytes:()=>[...Buffer.from(s)]}),DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],computeHmacSha256Signature:(s,k)=>[...crypto.createHmac('sha256',k).update(s).digest()]},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})}});
 for(const f of ['backend/Code.gs','backend/CloudflareReadAdapter.gs'])vm.runInContext(fs.readFileSync(f,'utf8'),context);
 const signed=(changes={})=>{const p={action:'cloudflareListSelf',subjectRef:sid,requestId:'test-request',timestamp:String(Math.floor(Date.now()/1000)),nonce:'synthetic_nonce_12345678',body:'{}',...changes};const hash=crypto.createHash('sha256').update(p.body).digest('hex');p.signature=crypto.createHmac('sha256',secret).update(['v2',p.action,p.subjectRef,p.requestId,p.timestamp,p.nonce,hash].join('\n')).digest('hex');return {parameter:p};};
 return {context,signed,props,tables,reads:()=>reads};
}
test('legacy raw read and write routes are denied',()=>{const s=setup();for(const action of ['getStudents','getStudent','getDeeds','setupFolders'])assert.equal(s.context.doGet({parameter:{action}}).code,'AUTHENTICATED_GATEWAY_REQUIRED');for(const action of ['approveDeed','submit_deed','bind_line','uploadImage','init_all_students'])assert.equal(s.context.doPost({postData:{contents:JSON.stringify({action})}}).code,'AUTHENTICATED_GATEWAY_REQUIRED');assert.equal(s.reads(),0);});
test('signed request matches v2 HMAC and returns only self without raw evidence',()=>{const s=setup(),r=s.context.doPost(s.signed());assert.equal(r.ok,true);assert.deepEqual(r.data.items.map(x=>x.deedId),['own']);assert.equal('studentId' in r.data.items[0],false);assert.equal('evidenceUrl' in r.data.items[0],false);});
test('tampered signature/body and expired request never read storage',()=>{for(const kind of ['signature','body','expired']){const s=setup(),e=s.signed(kind==='expired'?{timestamp:'1'}:{});if(kind==='signature')e.parameter.signature='0'.repeat(64);if(kind==='body')e.parameter.body='{"limit":1}';assert.equal(s.context.doPost(e).ok,false);assert.equal(s.reads(),0);}});
test('replay is rejected after first accepted request',()=>{const s=setup(),e=s.signed();assert.equal(s.context.doPost(e).ok,true);assert.equal(s.context.doPost(e).error,'ADAPTER_REPLAY_BLOCKED');});
test('non-staging, write action and subject overrides fail closed',()=>{let s=setup();s.props.APP_ENV='production';assert.equal(s.context.doPost(s.signed()).error,'ADAPTER_STAGING_REQUIRED');s=setup();assert.equal(s.context.doPost(s.signed({action:'cloudflareSubmitSelf'})).error,'ADAPTER_ACTION_DISABLED');assert.equal(s.context.doPost(s.signed({body:'{"studentId":"other"}'})).error,'ADAPTER_BODY_INVALID');assert.equal(s.reads(),0);});
test('duplicate master identity requires reconciliation',()=>{const s=setup();s.tables.Main_2569.push(s.tables.Main_2569[1]);assert.equal(s.context.doPost(s.signed()).error,'ADAPTER_IDENTITY_AMBIGUOUS');});
